import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = (props) => {
  const { data } = props;
  console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Current Map is</h1>
        <h2>
          {data?.current?.map}
          <br />
          for {data?.current?.DurationInMinutes} minutes and will end on{" "}
          {data?.current?.readableDate_end}
          <p>Remaining : {data?.current?.remainingMins} minutes</p>
        </h2>

        <h1 className={styles.title}>Next Map is</h1>
        <h2>
          {data?.next?.map}
          <br />
          for {data?.next?.DurationInMinutes} minutes and will start on{" "}
          {data?.next?.readableDate_start}
        </h2>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async (ctx) => {
  const key = process.env.NEXT_PUBLIC_API_KEY;
  const url = `https://api.mozambiquehe.re/maprotation?auth=${key}`;
  let data = null;
  try {
    const res = await fetch(url);
    if (res.ok) {
      data = await res.json();
    }
  } catch {
    data = null;
  }

  return {
    props: { data },
  };
};
